### ISSUE TITLE
subtitles timing drifts

### ISSUE THREAD

**Issue by ikke-t** [hirsivaja/plugin.video.areena#28] opened 2018-10-27 16:30 UTC
First of all, great plugin, thanks. I use it to watch series from areena, Arne Dahl right now. It plays fine on RasPi2 Kodi on XBian, but subtitle sync beed to be adjusted several times per episode.

It starts fine, but goes seconds off from timing after while. It starts by drifting a bit, but soon is 10 seconds behind. I adjust it from the subtitles menu, the timing sync feature.

It is not the only show. It happened also with Sorjonen, where I had it on by default, even I don't need it as it was in Finnish already.

I'm not sure if it is due pausing in middle, or does it somehow change stream or something in the middle. Or does it jus keep going a bit slow continously. I try to make sense of the behaviour.

Reproducal would be, start the mentioned series, and select the second subtitle from subs menu (Finnish, even though the string there is gibberish), and just let it play.

Version: Starting Kodi (17.6 Git:2017-11-18-433b93a). Platform: Linux ARM (Thumb) 32-bit

And plugin is the latest from github.

**Comment by ikke-t** [comment] 2018-10-27 16:39
Actually, after pausing to write down this issue, the delay just got to 23 secs. So perhaps pausing affects.

**Comment by hirsivaja** [comment] 2018-11-13 17:10
Could not reproduce this. During Arne Dahl the subtitles were in sync the whole time. Even pausing for long time did not make a difference.

**Comment by raspikodi4ever** [comment] 2019-04-08 18:23
I've had this issue too, but found a fix by stopping the playback and resuming playback again from where you left off - quick and easy. The subtitles may fall out of sync during longer pausing even when watching video from local files and the same fix works.

**Comment by hirsivaja** [comment] 2020-05-26 11:10
Closing, subtitle drift seems to be a "feature" in kodi itself

**Closed by hirsivaja** 2020-05-26 11:10 UTC
